name=HDSP 200x Driver
version=1.1
author=Matthew Haahr <matthew.haahr@gmail.com>
maintainer=Matthew Haahr <matthew.haahr@gmail.com>
sentence=Driver Library for HDSP-200x 4 Character 5x7 Dot Matrix Displays
paragraph=Arduino Driver Library to control HDSP-200x 4 Character 5x7 LED Dot Matrix Displays
category=Display
url=https://github.com/mjhaahr/HDSP-200X-Driver
architectures=*
includes=HDSP_200X.h
